### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by nightscape** [MaterializeInc/homebrew-materialize#92]
Hi all,

I just tried to follow the Materialized tutorial on Mac, but then noticed that the load generator does not work because the version installed by brew is ancient.
Would it be possible to update the version here?
Thank you!

**Comment by benesch** [comment]
Hi @nightscape, thanks for your interest in Materialize! We're currently transitioning to a new cloud-native product, which is unfortunately no longer possible to run on your local machine. You can request access here: https://materialize.com/register/.  In the meantime, you can follow the old getting started tutorial at https://materialize.com/docs/lts/get-started/, which will only use features that are available in v0.26.

**Comment by nightscape** [comment]
Ok, understood!
Will there be a self-hosted Kubernetes version, or is it Hyperscaler-only?
I intended to use Materialize on an Edge node in order to do aggregations and reduce the amount of data sent over the GSM network.

**Comment by benesch** [comment]
Hyperscaler only, I'm afraid. No current plans to offer a self-hosted Kubernetes version.

**Comment by nightscape** [comment]
Ok, thanks for letting me know. I'll evaluate the alternatives then.
